#!/usr/bin/env node

const fs = require("node:fs");
const path = require("node:path");
const JSZip = require("jszip");
const version = require("../package.json").version;

async function* tree(dir) {
  const dirents = await fs.promises.readdir(dir, { withFileTypes: true });
  for (const dirent of dirents) {
    const r = path.resolve(dir, dirent.name);
    if (dirent.isDirectory()) {
      yield* tree(r);
    } else {
      yield r;
    }
  }
}

const zipPackage = async (browser) => {
  const root = path.join(__dirname, "..", "dist", browser);
  const output = `vimmatic_v${version}_${browser}.zip`;

  const zip = new JSZip();

  for await (const f of tree(root)) {
    const relative = path.relative(root, f);
    console.error(`  adding: ${relative}`);
    const data = fs.readFileSync(f);
    zip.file(relative, data);
  }

  await new Promise((resolve, reject) => {
    zip
      .generateNodeStream({ type: "nodebuffer", streamFiles: true })
      .pipe(fs.createWriteStream(output))
      .on("finish", resolve)
      .on("error", reject);
  });
  console.error(`${output} created`);
};

(async () => {
  for (const browser of ["firefox", "chrome"]) {
    await zipPackage(browser);
  }
})();
