export const defaultJSONSettings = `{
  "keymaps": {
    "0": { "type": "scroll.home" },
    ":": { "type": "command.show" },
    "o": { "type": "command.show.open", "alter": false },
    "O": { "type": "command.show.open", "alter": true },
    "t": { "type": "command.show.tabopen", "alter": false },
    "T": { "type": "command.show.tabopen", "alter": true },
    "w": { "type": "command.show.winopen", "alter": false },
    "W": { "type": "command.show.winopen", "alter": true },
    "b": { "type": "command.show.buffer" },
    "a": { "type": "command.show.addbookmark", "alter": true },
    "k": { "type": "scroll.vertically", "count": -1 },
    "j": { "type": "scroll.vertically", "count": 1 },
    "h": { "type": "scroll.horizonally", "count": -1 },
    "l": { "type": "scroll.horizonally", "count": 1 },
    "<C-U>": { "type": "scroll.pages", "count": -0.5 },
    "<C-D>": { "type": "scroll.pages", "count": 0.5 },
    "<C-B>": { "type": "scroll.pages", "count": -1 },
    "<C-F>": { "type": "scroll.pages", "count": 1 },
    "gg": { "type": "scroll.top" },
    "G": { "type": "scroll.bottom" },
    "$": { "type": "scroll.end" },
    "d": { "type": "tabs.close" },
    "D": { "type": "tabs.close", "select": "left" },
    "x$": { "type": "tabs.close.right" },
    "!d": { "type": "tabs.close", "force": true },
    "u": { "type": "tabs.reopen" },
    "": { "type": "tabs.prev" },
    "": { "type": "tabs.next" },
    "H": { "type": "tabs.prev" },
    "L": { "type": "tabs.next" },
    "g0": { "type": "tabs.first" },
    "g$": { "type": "tabs.last" },
    "<C-6>": { "type": "tabs.prevsel" },
    "r": { "type": "tabs.reload", "cache": false },
    "R": { "type": "tabs.reload", "cache": true },
    "zp": { "type": "tabs.pin.toggle" },
    "zd": { "type": "tabs.duplicate" },
    "zi": { "type": "zoom.in" },
    "zo": { "type": "zoom.out" },
    "zz": { "type": "zoom.neutral" },
    "f": { "type": "hint.quick", "newTab": false },
    "F": { "type": "hint.quick", "newTab": true, "background": false },
    ";y": { "type": "hint.yankurl" },
    ";Y": { "type": "hint.yanklinktext" },
    ";i": { "type": "hint.openimage", "newTab": false },
    ";I": { "type": "hint.openimage", "newTab": true, "background": false },
    ";..": { "type": "hint.source", "newTab": false },
    ";V": { "type": "hint.source", "newTab": true },
    ";o": { "type": "hint.open" },
    ";t": { "type": "hint.tabopen" },
    ";w": { "type": "hint.winopen" },
    ";O": { "type": "hint.command.open" },
    ";T": { "type": "hint.command.tabopen" },
    ";W": { "type": "hint.command.winopen" },
    "m": { "type": "mark.set.prefix" },
    "'": { "type": "mark.jump.prefix" },
    "": { "type": "navigate.history.prev" },
    "": { "type": "navigate.history.next" },
    "[[": { "type": "navigate.link.prev" },
    "]]": { "type": "navigate.link.next" },
    "gu": { "type": "navigate.parent" },
    "gU": { "type": "navigate.root" },
    "gi": { "type": "focus.input" },
    "gf": { "type": "navigate.source" },
    "gh": { "type": "navigate.home" },
    "gH": { "type": "navigate.home", "newTab": true },
    "gr": { "type": "tabs.reader.toggle" },
    "y": { "type": "urls.yank" },
    "p": { "type": "urls.paste", "newTab": false },
    "P": { "type": "urls.paste", "newTab": true },
    "/": { "type": "find.start" },
    "n": { "type": "find.next" },
    "N": { "type": "find.prev" },
    "h": { "type": "visual.left", "count": 1},
    "l": { "type": "visual.right", "count": 1 },
    "e": { "type": "visual.word.end", "count": 1 },
    "w": { "type": "visual.word.next", "count": 1 },
    "b": { "type": "visual.word.back", "count": 1 },
    "Enter": { "type": "find.visual.start" },
    ".": { "type": "repeat" },
    "<S-Esc>": { "type": "addon.toggle.enabled" }
  },
  "search": {
    "default": "google",
    "engines": {
      "google": "https://google.com/search?q={}",
      "yahoo": "https://search.yahoo.com/search?p={}",
      "bing": "https://www.bing.com/search?q={}",
      "duckduckgo": "https://duckduckgo.com/?q={}",
      "twitter": "https://twitter.com/search?q={}",
      "wikipedia": "https://en.wikipedia.org/w/index.php?search={}"
    }
  },
  "properties": {
    "hintchars": "abcdefghijklmnopqrstuvwxyz",
    "smoothscroll": false,
    "complete": "sbh",
    "colorscheme": "system",
    "ignorecase": true,
    "findmode": "normal",
    "ignorenodes": true
  },
  "blacklist": [
  ],
  "styles": {
    "hint": {
      "background-color": "yellow",
      "border": "1px solid gold",
      "font-weight": "bold",
      "font-size": "12px",
      "color": "black"
    },
    "console": {
      "font-family": "monospace",
      "font-size": "12px"
    }
  }
}`;
