name: Build

on:
  push:
    branches-ignore:
      - master
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version-file: 'package.json'
        cache: 'pnpm'
    - run: pnpm install --frozen-lockfile
    - run: pnpm type-checks
    - run: pnpm lint
    - run: pnpm test
    - run: pnpm package
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: dist
        path: ./dist/

  test-e2e:
    name: E2E Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version-file: 'package.json'
        cache: 'pnpm'
    - name: Install xsel
      run: sudo apt-get install -y --no-install-recommends xsel
    - run: pnpm install --frozen-lockfile
    - run: pnpm exec playwright install firefox
    - run: pnpm build
    - run: pnpm exec webext-agent install --addon-ids vimmatic@i-beam.org
    - run: pnpm exec webext-agent create-addon --base-addon dist/firefox /tmp/vimmatic-mixedin
    - run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- pnpm run test:e2e --headed
