name: Build

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18.5.0'
        cache: 'yarn'
    - uses: ueokande/setup-firefox@latest
      with:
        firefox-version: 78.3.0esr
    - uses: ueokande/setup-geckodriver@latest
      with:
        geckodriver-version: 0.28.0
    - run: yarn install --immutable
    - run: yarn tsc
    - run: yarn lint
    - run: yarn test
    - run: yarn package

  test-e2e:
    name: E2E Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18.5.0'
        cache: 'yarn'
    - uses: ueokande/setup-firefox@latest
      with:
        firefox-version: 78.3.0esr
    - uses: ueokande/setup-geckodriver@latest
      with:
        geckodriver-version: 0.28.0
    - name: Install xsel
      run: sudo apt-get install -y --no-install-recommends xsel
    - run: yarn install --immutable
    - run: yarn build
    - run: $(npm bin)/webext-agent install
    - run: $(npm bin)/webext-agent create-addon --base-addon . /tmp/vimmatic-mixedin
    - name: Run test
      run: |
        export DISPLAY=:99

        geckodriver &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 >/dev/null 2>&1 &

        yarn test:e2e --headed

  deploy:
    name: Release to AMO
    needs: [build, test-e2e]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18.5.0'
        cache: 'yarn'
    - run: yarn install --immutable
    - run: yarn package
    - name: Release to AMO
      env:
        JWT_ISSUER: "${{ secrets.JWT_ISSUER }}"
        JWT_SECRET: "${{ secrets.JWT_SECRET }}"
      run: |
        version=$(jq -r '.version' manifest.json)
        ./script/deploy vimmatic@i-beam.org "$version" "vimmatic-${version}.zip"
